server:
  port: 8080

spring:
  mvc:
    view:
      suffix: .html
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring_vue_boilerplate
    username: sangmin
    password: 123456

jwt:
  header: Authorization
  secret: 67CV7IOB66+8MTk5MjEyMTdKV1TthqDtgbAg6rWs7ZiE7ZWY64ukLg== #시크릿 키는 256 bits (32 byte) 바꿔야함
  token-validity-in-seconds: 86400
